# Generated by Django 5.1.6 on 2026-05-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPersonal',
            fields=[
                ('id_pk', models.AutoField(db_column='id_pk', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='nombre_tipo', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Personal',
                'verbose_name_plural': 'Tipos de Personal',
                'db_table': 'tipos_personal',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_pk', models.AutoField(db_column='id_pk', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='cedula', max_length=8, unique=True)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('direccion_habitacional', models.TextField(db_column='direccion_habitacional')),
                ('correo', models.CharField(db_column='correo', max_length=150)),
                ('numero', models.CharField(db_column='numero', max_length=20)),
                ('estado', models.CharField(db_column='estado', max_length=20)),
                ('area_trabajo', models.CharField(db_column='area_trabajo', max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador'), ('Seguridad', 'Seguridad')], db_column='rol', max_length=50)),
                ('tipo_fk', models.ForeignKey(db_column='tipo_fk', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarios.tipospersonal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuariosAdministrativos',
            fields=[
                ('id_pk', models.AutoField(db_column='id_pk', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('id_usuario_fk', models.ForeignKey(db_column='id_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_administrativas', to='usuarios.empleado')),
            ],
            options={
                'verbose_name': 'Credencial Administrativa',
                'verbose_name_plural': 'Credenciales Administrativas',
                'db_table': 'usuarios_administrativos',
            },
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['cedula'], name='usuarios_cedula_dd8531_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado'], name='usuarios_estado_7877c9_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['tipo_fk'], name='usuarios_tipo_fk_014a8a_idx'),
        ),
    ]
