"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-clave-temporal-cambiar-en-produccion')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicaciones personalizadas
    'usuarios.apps.UsuariosConfig',
    'reconocimiento.apps.ReconocimientoConfig',
    'asistencia.apps.AsistenciaConfig',
    'notificaciones.apps.NotificacionesConfig',
    'reportes.apps.ReportesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.SecurityHeadersMiddleware',
    'config.middleware.RequestValidationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.DeveloperOnlyAccessMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ==============================================
# CONFIGURACIÓN DE BASE DE DATOS - MARIADB
# ==============================================

IS_DOCKER = os.path.exists('/.dockerenv')

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'identia_db',
        'USER': 'root',
        'PASSWORD': '',
        # Si detecta Docker usa host.docker.internal, si no, usa localhost
        'HOST': 'host.docker.internal' if IS_DOCKER else 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# ==============================================
# VERIFICACIÓN AUTOMÁTICA DE CONEXIÓN (MEJORADA)
# ==============================================

def verificar_conexion_db():
    """Verifica la conexión a la base de datos al iniciar Django"""
    import sys
    
    # Solo verificar en comandos específicos
    comandos_verificar = ['runserver', 'checkdb']
    
    if len(sys.argv) > 1 and sys.argv[1] in comandos_verificar:
        # Importar aquí para evitar warning de importación temprana
        from django.db import connections
        import time
        
        print("\n" + "="*60)
        print("🔍 VERIFICANDO CONEXIÓN A BASE DE DATOS")
        print("="*60)
        
        try:
            print(f"\n📡 Conectando a MariaDB...")
            
            conn = connections['default']
            conn.ensure_connection()
            
            with conn.cursor() as cursor:
                cursor.execute("SELECT DATABASE(), VERSION()")
                db_name, db_version = cursor.fetchone()
                
                cursor.execute("SHOW TABLES")
                tables = cursor.fetchall()
                table_names = [table[0] for table in tables]
            
            print("✅ CONEXIÓN EXITOSA!")
            print(f"   📊 Base de datos: {db_name}")
            print(f"   🌐 Host: {DATABASES['default']['HOST']}:{DATABASES['default']['PORT']}")
            print(f"   👤 Usuario: {DATABASES['default']['USER']}")
            print(f"   🚀 MariaDB Version: {db_version}")
            print(f"   📈 Tablas encontradas: {len(tables)}")
            
            # Mostrar solo las tablas principales del sistema
            tablas_sistema = ['usuarios', 'tipos_personal', 'usuarios_administrativos', 
                            'bitacora_asistencia', 'horarios_jornada', 'rostros_usuarios','notificaciones_leidas']
            print(f"   📋 Tablas del sistema:")
            for tabla in tablas_sistema:
                if tabla in table_names:
                    print(f"      ✓ {tabla}")
                else:
                    print(f"      ✗ {tabla} (no encontrada)")
            
            print("\n" + "="*60)
            return True
            
        except Exception as e:
            error_msg = str(e)
            print(f"❌ ERROR DE CONEXIÓN:")
            
            if "Access denied" in error_msg:
                print(f"   🔐 Error de autenticación")
                print(f"   Verifica usuario/contraseña en el archivo .env")
            elif "Can't connect" in error_msg:
                print(f"   🔌 No se puede conectar al servidor")
                print(f"   Asegúrate que MariaDB esté ejecutándose")
            elif "Unknown database" in error_msg:
                print(f"   📁 La base de datos no existe")
                print(f"   Ejecuta: CREATE DATABASE {DATABASES['default']['NAME']};")
            else:
                print(f"   💥 Error: {error_msg}")
            
            print("\n💡 SOLUCIÓN RÁPIDA:")
            print("1. Abre HeidiSQL y verifica que MariaDB esté ejecutándose")
            print("2. Crea la base de datos 'identia_db' si no existe")
            print("3. Verifica las credenciales en el archivo .env")
            print("4. Revisa que el puerto 3306 esté accesible")
            
            print("\n" + "="*60)
            return False
    
    return True

# Ejecutar verificación automática (sin warnings)
if os.environ.get('RUN_MAIN') == 'true':
    verificar_conexion_db()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================
# CONFIGURACIÓN DE AUTENTICACIÓN PERSONALIZADA
# ==============================================

# Usar el modelo User por defecto de Django
AUTH_USER_MODEL = 'auth.User'

# Backends de autenticación (nuestro custom primero)
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.CustomAuthenticationBackend',  # Nuestro backend personalizado
    'django.contrib.auth.backends.ModelBackend',      # Backend por defecto
]

# URLs de autenticación
LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/dashboard/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'

# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora en segundos
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = 'identia_sessionid'
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# ==============================================
# CONFIGURACIÓN DE LOGGING
# ==============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'usuarios': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Reducir log de queries para desarrollo
            'propagate': False,
        },
    },
}


# ==============================================
# CONFIGURACIÓN INTERNACIONALIZACIÓN
# ==============================================

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'  # Cambia según tu zona horaria

USE_I18N = True

USE_TZ = True

# Formato de fechas para España/Latinoamérica
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'


# ==============================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ==============================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crear directorios si no existen
os.makedirs(BASE_DIR / 'static', exist_ok=True)
os.makedirs(BASE_DIR / 'media', exist_ok=True)
os.makedirs(BASE_DIR / 'logs', exist_ok=True)


# ==============================================
# CONFIGURACIONES DE SEGURIDAD (DESARROLLO)
# ==============================================

# En producción, cambiar estas configuraciones:
CSRF_COOKIE_SECURE = False  # True en producción
CSRF_COOKIE_HTTPONLY = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'


# ==============================================
# CONFIGURACIONES ADICIONALES
# ==============================================

# Configuración para servir archivos en desarrollo
if DEBUG:
    INSTALLED_APPS += ['django_extensions']  # Herramientas de desarrollo
    
    # Deshabilitar caché de plantillas para ver cambios en tiempo real
    TEMPLATES[0]['OPTIONS']['debug'] = True
    
    # Configuración para desarrollo
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================
# CONFIGURACIÓN PERSONALIZADA DE LA APLICACIÓN
# ==============================================

# Configuración para reconocimiento facial (ACTUALIZADA)
FACIAL_RECOGNITION_CONFIG = {
    'MODEL_PATH': str(BASE_DIR / 'models' / 'buffalo_l'),
    'EMBEDDING_SIZE': 512,
    'SIMILARITY_THRESHOLD': 0.3,  # ¡CAMBIADO DE 0.6 A 0.4!
    'MIN_FACE_SIZE': 100,
    'DETECTION_CONFIDENCE': 0.5,
}

# Configuración de la terminal
TERMINAL_CONFIG = {
    'NOMBRE': 'Terminal de Transporte Principal',
    'HORARIO_APERTURA': '05:00',
    'HORARIO_CIERRE': '22:00',
    'TOLERANCIA_ENTRADA': 15,  # minutos
    'TOLERANCIA_SALida': 15,   # minutos
}

# Crear directorios para configuraciones personalizadas
os.makedirs(FACIAL_RECOGNITION_CONFIG['MODEL_PATH'], exist_ok=True)
os.makedirs(BASE_DIR / 'reconocimiento', exist_ok=True)  # CORREGIDO: La app está en la raíz


# ==============================================
# CONFIGURACIÓN DE SEGURIDAD ADICIONAL
# ==============================================

# Configuración de cookies de sesión
SESSION_COOKIE_SECURE = True  # Solo enviar cookies sobre HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevenir acceso a cookies via JavaScript
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevenir CSRF

# Configuración de cookies de autenticación
AUTH_COOKIE_SECURE = True
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SAMESITE = 'Strict'

# Prevenir acceso a las herramientas de admin desde producción
ADMIN_ENABLED = DEBUG  # Solo disponible en modo DEBUG

# Validación de URLs seguras
SECURE_REDIRECT_EXEMPT = []

# SSL/TLS
SECURE_SSL_REDIRECT = not DEBUG  # Redirigir HTTP a HTTPS en producción
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy (CSP)
# Nota: Ajusta según las necesidades de tu aplicación
if DEBUG:
    # En desarrollo, permitir todo
    pass
else:
    # En producción, configurar CSP estricto
    pass

# Logging de seguridad
LOGGING['handlers']['security_file'] = {
    'level': 'WARNING',
    'class': 'logging.FileHandler',
    'filename': str(BASE_DIR / 'logs' / 'security.log'),
    'formatter': 'verbose',
}

# Registro de intentos de acceso sospechoso
SECURITY_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'security.log'),
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}